language: c

before_install:
  - echo "deb http://build.openmodelica.org/apt `lsb_release -cs` nightly" | sudo tee /etc/apt/sources.list.d/openmodelica.list 
  - wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add - 
  - sudo apt-get update --fix-missing -qq

install:
  - sudo apt-get install omc

#before_script:

script:
  - mkdir build
  - cd build
  - cmake .. && make && ctest

#after_success:
#  - coveralls
